@echo off
SET _BIN_DIR=%_BUILDBOT_SVN_PATH%\_BinR
SET _BIN_PACK_DIR=%_BUILTBOT_PUBLISH_PACK_PATH%

ECHO %_BIN_PACK_DIR%
IF NOT EXIST %_BIN_PACK_DIR% MKDIR %_BIN_PACK_DIR%

echo on
COPY /Y %_BIN_DIR%\KBSS_WLFS.DLL %_BIN_PACK_DIR%
COPY /Y %_BIN_DIR%\KCBPSPD_wlfs.xml %_BIN_PACK_DIR%
